name: CD
on:
    pull_request:
        types: [closed]
        branches: [release]

permissions:
    id-token: write  # Required for OIDC
    contents: read
    pages: write      # to deploy to Pages

jobs:
    deploy:
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: release
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
                registry-url: 'https://registry.npmjs.org'
            # Ensure npm 11.5.1 or later is installed
            - run: npm install -g npm@latest
            - run: npm i
            - run: npm run build:prod
            - run: npm publish

    updateDocs:
        if: github.event.pull_request.merged
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: release
            - uses: actions/setup-node@v4
              with:
                node-version: '22'
            - run: npm ci
            - run: npm run build:prod
            - uses: actions/configure-pages@v5
            - uses: actions/upload-pages-artifact@v3
              with:
                path: docs/generated
            - uses: actions/deploy-pages@v4