name: CD
on:
    pull_request:
        types: [closed]
        branches: [release]

jobs:
    deploy:
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                ref: release
            - run: npm ci
            - run: npm run build
            - uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}