name: CI
on:
    push:
        branches-ignore: [release]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm run build:prod
            - run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install PostgreSQL 17
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql-common ca-certificates curl
                printf '\n' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
                sudo apt-get update
                sudo apt-get install -y postgresql-client-17
            - run: npm ci
            - run: npm run build:prod
            - run: npm run test:ci