name: CI
on: 
    push:
        branches-ignore: [release]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm run build
            - run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # install a client that matches the server version your tests use (Postgres 17.x)
            - name: Install PostgreSQL 17 client
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql-client-17
            - run: npm ci
            - run: npm run build
            - run: npm run test:ci